// <auto-generated />
using CandidateTesting.JeffersonBompadre.AdjacentMaxDistance.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CandidateTesting.JeffersonBompadre.AdjacentMaxDistance.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("CandidateTesting.JeffersonBompadre.AdjacentMaxDistance.Domain.Model.Indice", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("Indice_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValueId")
                        .HasColumnName("Value_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK_TBL_Indice");

                    b.HasIndex("ValueId");

                    b.ToTable("TBL_Indice");
                });

            modelBuilder.Entity("CandidateTesting.JeffersonBompadre.AdjacentMaxDistance.Domain.Model.ValueInArray", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Value_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnName("Value_Array")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK_TBL_ValueArray");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasName("IDX_Value");

                    b.ToTable("TBL_ValueArray");
                });

            modelBuilder.Entity("CandidateTesting.JeffersonBompadre.AdjacentMaxDistance.Domain.Model.Indice", b =>
                {
                    b.HasOne("CandidateTesting.JeffersonBompadre.AdjacentMaxDistance.Domain.Model.ValueInArray", "ValueInArray")
                        .WithMany("Indices")
                        .HasForeignKey("ValueId")
                        .HasConstraintName("FK_Indice_ValueArray")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
